# Generated by Django 2.2.7 on 2019-11-27 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_data',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 11, 27, 19, 55, 48, 729569)),
        ),
    ]
