# Generated by Django 2.2.7 on 2019-12-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userview',
            options={'managed': True},
        ),
    ]
