# Generated by Django 2.2.7 on 2019-12-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserView',
            new_name='StuUserView',
        ),
        migrations.AlterModelTable(
            name='stuuserview',
            table='account_stu_user_view',
        ),
    ]
