# Generated by Django 2.2.7 on 2019-12-12 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentselectcourse',
            name='course_id',
            field=models.ForeignKey(default='161130205', on_delete=django.db.models.deletion.CASCADE, to='edu_admin.Course'),
        ),
    ]
