# Generated by Django 2.2.7 on 2019-11-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0003_auto_20191125_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_no',
            field=models.IntegerField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
