# Generated by Django 2.2.7 on 2019-11-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0004_auto_20191125_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAccount',
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_no',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
