# Generated by Django 2.2.7 on 2019-11-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0006_auto_20191127_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='select',
            name='test',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
