# Generated by Django 2.2.7 on 2019-12-10 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('room_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('place', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('owner', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=20)),
                ('course_belong', models.CharField(max_length=50, null=True)),
                ('credit', models.IntegerField(default=0)),
                ('course_char', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SelectCourse',
            fields=[
                ('select_course_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_num', models.IntegerField()),
                ('course_remain', models.IntegerField(default=100)),
                ('time', models.CharField(max_length=50)),
                ('term', models.CharField(max_length=50)),
                ('scclass', models.CharField(max_length=100, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_admin.Course')),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_admin.Classroom')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSelectCourse',
            fields=[
                ('select_id', models.CharField(auto_created=True, max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=None, null=True)),
                ('is_reread', models.BooleanField(default=False)),
                ('select_course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='edu_admin.SelectCourse')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
