# Generated by Django 2.2.7 on 2019-11-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_no', models.CharField(max_length=12)),
                ('stu_name', models.CharField(max_length=8)),
                ('stu_school_no', models.CharField(max_length=20)),
                ('stu_major_no', models.CharField(max_length=20)),
                ('stu_class', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('stu_no',),
            },
        ),
    ]
