# Generated by Django 2.2.7 on 2019-11-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_no',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
