# Generated by Django 2.2.7 on 2019-11-25 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0002_auto_20191125_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stu_major_no',
            new_name='stu_major',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stu_school_no',
            new_name='stu_school',
        ),
    ]
