# Generated by Django 2.2.7 on 2019-12-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0008_remove_select_test'),
        ('edu_admin', '0003_course_description'),
    ]

    operations = [
    ]
