# Generated by Django 2.2.7 on 2019-11-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0008_remove_select_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
