# Generated by Django 2.2.7 on 2019-11-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0009_course_course_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_belong',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
