# Generated by Django 2.2.7 on 2019-11-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0010_auto_20191130_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_belong',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_char',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='select',
            name='select_id',
            field=models.CharField(auto_created=True, max_length=20),
        ),
    ]
