# Generated by Django 2.2.7 on 2019-11-30 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0011_auto_20191130_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_belong',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_char',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='edu_admin.Classroom'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
