# Generated by Django 2.2.7 on 2019-12-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_admin', '0012_auto_20191130_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_belong',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
