# Generated by Django 2.2.7 on 2019-12-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191127_1955'),
        ('account', '0003_scorecalculateview'),
    ]

    operations = [
    ]
